application-insights.tf, variables.tf
Update App insights
Update App insights
**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```
=> Update App insights

variables.tf
Fix subscriptions
Fix subscriptions
**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```
=> Fix subscriptions

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/LAU-630
Disabling slack channel
**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```
=> LAU-630 disabling slack channel for time being

.github/renovate.json, key-vault.tf
Set s2s secret via terraform
Set s2s secret via terraform
=> Set s2s secret via terraform

alerts.tf
LAU-789
Make short name to 12 chars as that is the limit
=> make short name short

aat.tfvars, alerts.tf, demo.tfvars, ithc.tfvars, key-vault.tf, main.tf, perftest.tfvars, prod.tfvars, provider.tf, variables.tf
=> LAU-913 enabling alerts in demo

alerts.tf
Changing short name as master build is complaining
=> LAU-915 disposer shared

alerts.tf
Alert short name within 12 chars
=> LAU-915 alert name with 12 chars

alerts.tf
Creating alert in correct resource group
=> LAU-913 creating alert in correct resource group

alerts.tf
=> LAU-913 changing alert name

alerts.tf, demo.tfvars, prod.tfvars
Enable alert on prod and disable on demo
=> LAU-913 Creating and enabling alert on prod and disable on demo

alerts.tf, demo.tfvars, key-vault.tf, variables.tf
https://tools.hmcts.net/jira/browse/LAU-924
This change is to add new summary alert and push this on slack channel
=> LAU-924 adding summary alert and enable on demo

alerts.tf, key-vault.tf
=> LAU-913 moving alert email to secret

variables.tf
Disposer to raise alert early around 7am
=> raise-alert-early

alerts.tf, variables.tf
Raising summary alert early and failure alert to diagnose early
=> Creating alerts early

variables.tf
https://tools.hmcts.net/jira/browse/LAU-947
Fixing time windows to 24 hours
=> Fix time window to 24 hours

variables.tf
https://tools.hmcts.net/jira/browse/LAU-947
Frequency back to 1440
Slack alerts testing
=> LAU-947 frequency back to 1440

alerts.tf
https://tools.hmcts.net/jira/browse/LAU-947
Remove alert for Idam disposer
=> LAU-947 remove Idam disposer alert

alerts.tf
https://tools.hmcts.net/jira/browse/LAU-947
Adding alert back
=> LAU-947 adding alert back

alerts.tf
https://tools.hmcts.net/jira/browse/LAU-987
To pick traces from Thursday morning to Friday morning for 24 hours
=> Update alerts.tf to pick traces from Friday as well 

alerts.tf
https://tools.hmcts.net/jira/browse/LAU-987
Update Summary alert to pick summary for Friday as well
=> Update alerts.tf to pick Friday on Summary alert as well **DO NOT MERGE TILL MONDAY 7:11**

CODEOWNERS, README.md, application-insights.tf, key-vault.tf, state.tf
https://tools.hmcts.net/jira/browse/LAU-1105
Added s2s for fee and pay disposer
=> LAU-1105 add s2s for fee and pay application
